<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AssemblyName>Eitmad.WindowsShell</AssemblyName>
    <RootNamespace>Eitmad.WindowsShell</RootNamespace>
    <ApplicationIcon />
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="generated\**\*.cs" />
    <Compile Remove="tests\**\*.cs" />
    <ProjectReference Include="..\..\platform-adapters\windows\Eitmad.Platform.Windows.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\ShowroomHero.png" />
  </ItemGroup>
</Project>
